scripts/gui/a2/urls.py
from django.conf.urls import url
from .views import (
benchmark_list, benchmark_create, benchmark_detail, benchmark_update, benchmark_delete,benchmark_start, benchmark_finish,benchmark_stop,
crawler_list, crawler_create, crawler_delete, crawler_update, crawler_detail, crawler_stop, crawler_start, crawler_finish,
benchmarkResult_create, benchmarkResult_delete,benchmark_result_detail,
crawler_result_create, crawlerResult_delete,  crawler_result_detail,
crawler_settings_create, crawler_settings_delete, crawler_settings_update, crawler_settings_detail,
)

app_name = 'a2'
urlpatterns = [
    url(r'^benchmark/$', benchmark_list, name='benchmark_list'),
    url(r'^benchmark/create/', benchmark_create, name='benchmark_create'),
    url(r'^benchmark/(?P<id>\d+)/$', benchmark_detail, name='benchmark_detail'),
    url(r'^benchmark/(?P<id>\d+)/edit/$', benchmark_update, name='benchmark_update'),
    url(r'^benchmark/(?P<id>\d+)/delete/$', benchmark_delete, name='benchmark_delete'),
    url(r'^benchmark/(?P<id>\d+)/start/$', benchmark_start, name='benchmark_start'),
    url(r'^benchmark/(?P<id>\d+)/finish/$', benchmark_finish, name='benchmark_finish'),
    url(r'^benchmark/(?P<id>\d+)/stop/$', benchmark_stop, name='benchmark_stop'),
    url(r'^benchmark/result_create/$', benchmarkResult_create, name='benchmarkResult_create'),
    url(r'^benchmark/result_detail/(?P<id>\d+)/delete/$', benchmarkResult_delete, name='benchmarkResult_delete'),
    url(r'^benchmark/result_detail/(?P<id>\d+)/$', benchmark_result_detail, name='benchmark_result_detail'),
    # url(r'^benchmark/result/$', benchmarkResult_delete, name='benchmarkResult_delete'),

    url(r'^crawler/$', crawler_list, name='crawler_list'),
    url(r'^crawler/create/', crawler_create, name='crawler_create'),
    url(r'^crawler/(?P<id>\d+)/$', crawler_detail, name='crawler_detail'),
    url(r'^crawler/(?P<id>\d+)/edit/$', crawler_update, name='crawler_update'),
    url(r'^crawler/(?P<id>\d+)/delete/$', crawler_delete, name='crawler_delete'),
    url(r'^crawler/(?P<id>\d+)/start/$', crawler_start, name='crawler_start'),
    url(r'^crawler/(?P<id>\d+)/stop/$', crawler_stop, name='crawler_stop'),
    url(r'^crawler/(?P<id>\d+)/finish/$', crawler_finish, name='crawler_finish'),

    url(r'^crawler/crawlerResult/create/', crawler_result_create, name='crawler_result_create'),
    url(r'^crawler/crawlerResult/(?P<id>\d+)/delete/$', crawlerResult_delete, name='crawlerResult_delete'),
    url(r'^crawler/crawlerResult/(?P<id>\d+)/$', crawler_result_detail, name='crawler_result_detail'),
    url(r'^crawler/(?P<id>\d+)/crawlerSettings/create/$', crawler_settings_create, name='crawler_settings_create'),
    url(r'^crawler/(?P<id>\d+)/crawlerSettings/delete/$', crawler_settings_delete, name='crawler_settings_delete'),
    url(r'^crawler/(?P<id>\d+)/crawlerSettings/edit/$', crawler_settings_update, name='crawler_settings_update'),
    url(r'^crawler/(?P<id>\d+)/crawlerSettings/$', crawler_settings_detail, name='crawler_settings_detail'),


]

scripts/gui/gui/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^a2/', include("a2.urls", namespace='a2')),
]

scripts/gui/templates/crawler/base.html
{% load staticfiles %}
<!-- DOCTYPE html -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block head_title %} Try Django 1.9 {% endblock head_title %}
    </title>
    <link rel='stylesheet' href='{% static "css/base.css" %}' >
    <link rel='stylesheet' href='{% static "css/bootstrap.css" %}' >
    <!-- Latest compiled and minified CSS -->
<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">-->

<!-- Optional theme -->
<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">-->

</head>
<body>
    {% block nav %}
    <ul id="nav">
        <li>{% block nav-home %}<a href="{% url home %}">Home</a>{% endblock %}</li>
        <li>{% block nav-about %}<a href="{% url about %}">About</a>{% endblock %}</li>
        <li>{% block nav-contact %}<a href="{% url contact %}">Contact</a>{% endblock %}</li>
    </ul>
    {% endblock %}
{% include "includes/messages_display.html" %}
<div class='container'>
    {% block content %}

    {% endblock content %}
</div>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>

scripts/gui/templates/crawler/crawler_detail.html
{% extends "general/base.html" %}
{% block head_title %} {{ instance.title }} | {{ block.super}} {% endblock head_title %}
{% block content %}
    {% include "includes/topNav.html" %}
    <div class='col-sm-10 col-sm-offset-1'>
        <h1> {{instance.name}}:<br></h1>
        <hr>
        <div class="row" style="background-color:#eeeeee; padding: 20px">
            <div class="row" style="padding: 5px">
                <div class="col-md-3">Starturl:</div><div class="col-md-4"> {{ instance.starturl }}</div>
            </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">entitytyp: </div><div class="col-md-4"> {{ instance.entitytyp }}</div>
            </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">Datensätze speichern: </div><div class="col-md-4"> {{ instance.insertIntoDB }}</div>
            </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">Postprocessing aktivieren: </div><div class="col-md-4"> {{ instance.doPostprocessing }}</div>
            </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">Datenbank bereinigen: </div><div class="col-md-4"> {{ instance.clearDatabase }}</div>
            </div>
        </div>
        <hr>
        <h2>Settings: </h2>
        <div class="row" style="background-color:#eeeeee; padding: 20px">
            {% if instance.entitytyp == 'EC' %}
            <div class="row" style="padding: 5px">
                <div class="col-md-3">CodeElementClass: </div><div class="col-md-4"> {{ settings.attr01 }}</div>
                </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">CodeElementElem: </div><div class="col-md-4"> {{ settings.attr02 }}</div>
            </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">ExplanationElementElement: </div><div class="col-md-4"> {{ settings.attr03 }}</div>
                </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">ExplanationElementClass: </div><div class="col-md-4"> {{ settings.attr04 }}</div>
            </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">SolutionElementElement: </div><div class="col-md-4"> {{ settings.attr05 }}</div>
                </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">solutionElementClasse: </div><div class="col-md-4"> {{ settings.attr06 }}</div>
            </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">mydomain: </div><div class="col-md-4"> {{ settings.attr07 }}</div>
                </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">Myurl: </div><div class="col-md-4"> {{ settings.attr08 }}</div>
            </div>
            {% else %}
            <div class="row" style="padding: 5px">
                <div class="col-md-3">Area['class']: </div><div class="col-md-4"> {{ settings.attr01 }}</div>
                </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">Area['element']: </div><div class="col-md-4"> {{ settings.attr02 }}</div>
            </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">Name['class']: </div><div class="col-md-4"> {{ settings.attr03 }}</div>
                </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">Name['element']: </div><div class="col-md-4"> {{ settings.attr04 }}</div>
            </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">Info['class']: </div><div class="col-md-4"> {{ settings.attr05 }}</div>
                </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">Info['element']: </div><div class="col-md-4"> {{ settings.attr06 }}</div>
            </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">Phone['class']: </div><div class="col-md-4"> {{ settings.attr07 }}</div>
                </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">Phone['element']: </div><div class="col-md-4"> {{ settings.attr08 }}</div>
            </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">Mail['class']: </div><div class="col-md-4"> {{ settings.attr09 }}</div>
                </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">Mail['element']: </div><div class="col-md-4"> {{ settings.attr10 }}</div>
            </div>
            {% endif %}
        </div>
    </div>
    <div class='col-sm-10 col-sm-offset-1'>
        <div class="row" style="padding:10px">
            <div class="col-md-2"><a href="{% url 'a2:crawler_list' %}" class="btn btn-primary" role="button">OK</a></div>
            <div class="col-md-2"><a href="{{obj.get_absolute_url}}edit" class="btn btn-default" role="button">Bearbeiten</a></div>
            <div class="col-md-2"><a href="{{obj.get_absolute_url}}delete" class="btn btn-default" role="button">Löschen</a></div>
        </div>
    </div>
{% endblock content %}

scripts/gui/templates/crawler/crawler_form.html
{% extends "general/base.html" %}
<div class='col-sm-10 col-sm-offset-2'>

{% block content %}
    {% include "includes/topNav.html" %}
    <form method='POST' action=''>{% csrf_token %}
        <h1>Crawler anlegen</h1>
        <hr>
        <div class='col-sm-10 col-sm-offset-1'>
            {% for field in form %}
                {{ field.errors }}
                <div class="row">
                    <div class="col-md-3">{{ field.label_tag }}</div>
                    <div class="col-md-4">{{ field }}</div>
                </div>
                {% if field.help_text %} <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            {% endfor %}
            {% if field.help_text %}
            [% else %}
            {% endif %}
        <hr>
        {% if form.instance.pk %}
        <input type='submit' value='Updaten' class="btn btn-default"/>
        {% else %}
        <input type='submit' value='next' class="btn btn-default"/>
        {% endif %}
        </div>
    </form>
{% endblock content %}
</div>

scripts/gui/templates/crawler/crawler_list.html
{% extends "general/base.html" %}
{% block content %}
{% include "includes/topNav.html" %}
<div class="col-md-6 col-md-offset-0">
    <div class="row">
        <h1>Crawler</h1>
        <hr>
    </div>
        {% for obj in object_list %}
        {% if obj.isrunning %}
            <div class="col-md-12" style="background-color:#e5ffe5; border: 1px solid #007f00; border-radius: 15px; margin-bottom: 15px">
        {% else %}
            <div class="col-md-12" style="background-color:#eeeeee; border: 1px solid #ccc; border-radius: 15px; margin-bottom: 15px">
        {% endif %}
              <div class="row">
                  <div class="col-md-12">
                    <h1><a href='{{obj.get_absolute_url}}'>{{ obj.name }}</a></h1>
                      <small>
                          {% if obj.isrunning %}
                            der Crawler läuft
                          {% else %}
                            der Crawler läuft nicht
                          {% endif %}
                      </small>
                  </div>
              </div>

              <div class="row">
                  <div class="col-md-4">Starturl: </div>
                  <div class="col-md-8"><a href="{{ obj.starturl }}">{{ obj.starturl }}</a></div>
              </div>
              <div class="row">
                  <div class="col-md-4">entitytyp: </div>
                  <div class="col-md-8">{{ obj.entitytyp }}</a></div>
              </div>
              <div class="row" style="padding:15px;">
                  <p><a href="{{obj.get_absolute_url}}" class="btn btn-primary" role="button">Detailansicht</a>
                  <a href="{{obj.get_absolute_url}}edit" class="btn btn-default" role="button">Bearbeiten</a>
                  <a href="{{obj.get_absolute_url}}delete" class="btn btn-default" role="button">Löschen</a>
                  {% if obj.isrunning %}
                    <a href="{{obj.get_absolute_url}}stop" class="btn btn-default" role="button">Stop</a>
                  {% else %}
                    <a href="{{obj.get_absolute_url}}start" class="btn btn-default" role="button">Start</a></p>
                  {% endif %}

                  <!--<a href="{{obj.get_settings}}" class="btn btn-default" role="button">Settings</a></p>-->
              </div>
          </div>
    {% endfor %}
    <p style="text-align:center;"><a href="{{obj.get_absolute_url}}create" class="btn btn-primary" role="button">Crawler anlegen</a></p>
</div>
<div class="col-md-6 col-md-offset-0">
    <div class="row">
        <h1>bisherige Resultate</h1>
        <hr>
            {% for obj in crawler_result_object_list %}
          <div class="col-md-12" style="background-color:#eeeeee; border: 1px solid #ccc; border-radius: 15px; margin-bottom: 15px">
              <div class="row">
                  <div class="col-md-12">
                    <h1>{{ obj.crawler }}<small> {{obj.created}}</small></h1>
                  </div>
              </div>
              <div class="row">
                  <div class="col-md-3">dataset: </div>
                  <div class="col-md-3">{{ obj.entitytyp }}</div>
              </div>
              <div class="row">
                  <div class="col-md-3">totalpages: </div>
                  <div class="col-md-3">{{ obj.totalpages }}</div>
              </div>
              <div class="row">
                  <div class="col-md-3">crawledpages: </div>
                  <div class="col-md-3">{{ obj.crawledpages }}</div>
              </div>
                <div class="row" style="padding:15px;">
                  <p><a href="{{obj.get_absolute_url}}" class="btn btn-primary" role="button">Detailansicht</a>
                  <a href="{{obj.get_absolute_url}}delete" class="btn btn-default" role="button">Löschen</a>
              </div>
          </div>
    {% endfor %}
        <hr>
    </div>
</div>
    {% endblock content %}
</div>

scripts/gui/templates/crawler/crawler_result.html
{% extends "general/base.html" %}
{% block head_title %} {{ instance.title }} | {{ block.super}} {% endblock head_title %}
{% block content %}
    {% include "includes/crawlNav.html" %}
    <div class='col-sm-10 col-sm-offset-1'>
        <h1> Detailansicht von Crawler: {{instance.name}}<br> <small>{{ instance.created }}</small><br></h1>
        <hr>
        <div class="row" style="background-color:#eeeeee; padding: 20px">
            <div class="row" style="padding: 5px">
                <div class="col-md-3">ID:</div><div class="col-md-4"> {{ instance.id }}</div>
            </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">Name des Crwalers: </div><div class="col-md-4"> {{ instance.name }}</div>
            </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">starturl: </div><div class="col-md-4"> {{ instance.starturl }}</div>
            </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">gesamtes Web: </div><div class="col-md-4"> {{ instance.everywhere }}</div>
            </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">logging: </div><div class="col-md-4"> {{ instance.logging }}</div>
            </div>
            <h2>Zeitstempel: </h2>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">erstellt: </div><div class="col-md-4"> {{ instance.created }}</div>
                </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">updated: </div><div class="col-md-4"> {{ instance.updated }}</div>
            </div>
        </div>
    </div>
    <div class='col-sm-10 col-sm-offset-1'>
        <div class="row" style="padding:10px">
            <div class="col-md-2"><a href="{% url 'a2:crawler_list' %}" class="btn btn-primary" role="button">OK</a></div>
          <div class="col-md-2"><a href="{{obj.get_absolute_url}}edit" class="btn btn-default" role="button">Bearbeiten</a></div>
          <div class="col-md-2"><a href="{{obj.get_absolute_url}}delete" class="btn btn-default" role="button">Löschen</a></div>
    </div>
</div>
{% endblock content %}

scripts/gui/templates/crawler/crawler_result_detail.html
{% extends "general/base.html" %}
{% block head_title %} {{ instance.title }} | {{ block.super}} {% endblock head_title %}
{% block content %}
{% include "includes/topNav.html" %}
<div class='col-sm-10 col-sm-offset-0'>
    <h1> Detailansicht vom Crawler Ergebnis: <br>{{instance.name}} <br><small>vom {{ instance.created }}</small><br></h1>
    <hr>
    {% for obj in records %}
    <div class='col-sm-3 col-sm-offset-0'>{{obj.created}}</div>
    <div class='col-sm-9 col-sm-offset-0'> <a href="{{obj.url}}">{{obj.url}}</a></div>

    {% endfor %}
    <hr>
    <div class='col-sm-12 col-sm-offset-0' style="padding:10px; text-align:center;">
        <p>
          <a href="{% url 'a2:crawler_list' %}" class="btn btn-primary" role="button">OK</a>
          <a href="{{obj.get_absolute_url}}delete" class="btn btn-default" role="button">Löschen</a>
        </p>
    </div>
</div>
{% endblock content %}

scripts/gui/templates/crawler/crawler_settings_detail.html
{% extends "general/base.html" %}
{% block head_title %} {{ instance.title }} | {{ block.super}} {% endblock head_title %}
{% block content %}
    {% include "includes/topNav.html" %}
    <div class='col-sm-10 col-sm-offset-1'>
        <h1> CrawlerSettings: {{instance.name}}<br> <small>{{ instance.created }}</small><br></h1>
        <hr>
        <div class="row" style="background-color:#eeeeee; padding: 20px">
            <div class="row" style="padding: 5px">
                <div class="col-md-3">ID:</div><div class="col-md-4"> {{ instance.id }}</div>
            </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">Name des Crwalers: </div><div class="col-md-4"> {{ instance.name }}</div>
            </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">starturl: </div><div class="col-md-4"> {{ instance.starturl }}</div>
            </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">gesamtes Web: </div><div class="col-md-4"> {{ instance.everywhere }}</div>
            </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">logging: </div><div class="col-md-4"> {{ instance.logging }}</div>
            </div>
            <h2>Zeitstempel: </h2>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">erstellt: </div><div class="col-md-4"> {{ instance.created }}</div>
                </div>
            <div class="row" style="padding: 5px">
                <div class="col-md-3">updated: </div><div class="col-md-4"> {{ instance.updated }}</div>
            </div>
        </div>
    </div>
    <div class='col-sm-10 col-sm-offset-1'>
        <div class="row" style="padding:10px">
            <div class="col-md-2"><a href="{% url 'a2:crawler_list' %}" class="btn btn-primary" role="button">OK</a></div>
            <div class="col-md-2"><a href="{{obj.get_absolute_url}}edit" class="btn btn-default" role="button">Bearbeiten</a></div>
            <div class="col-md-2"><a href="{{obj.get_absolute_url}}delete" class="btn btn-default" role="button">Löschen</a></div>
        </div>
    </div>
{% endblock content %}

scripts/gui/templates/crawler/crawler_settings_form.html
{% extends "general/base.html" %}
<div class='col-sm-10 col-sm-offset-2'>

{% block content %}
    {% include "includes/topNav.html" %}

    <form method='POST' action=''>{% csrf_token %}
        <h1>Crawlereinstellungen</h1>
        <hr>
        {% if crawler.entitytyp == 'Error Codes' %}
               <div class="fieldWrapper">
            <div class='col-sm-12 col-sm-offset-1'>
                <div class="col-md-2">
                    <label for="{{ form.attr01.id_for_label }}">errorUrl:</label>
                </div>
                <div class="col-md-10">
                    {{ form.attr01 }}
                </div>
            </div>
        </div>
        <div class="fieldWrapper">
            <div class='col-sm-12 col-sm-offset-1'>
                <div class="col-md-2">
            <label for="{{ form.attr02.id_for_label }}">errorBrand:</label>
                </div>
                <div class="col-md-10">
            {{ form.attr02 }}
                </div>
            </div>
        </div>
        <div class="fieldWrapper">
            <div class='col-sm-12 col-sm-offset-1'>
                <div class="col-md-2">
            <label for="{{ form.attr03.id_for_label }}">errorArea['elem']:</label>
                    </div>
                <div class="col-md-10">
            {{ form.attr03  }}
                </div>
            </div>
        </div>
        <div class="fieldWrapper">
            <div class='col-sm-12 col-sm-offset-1'>
                <div class="col-md-2">
            <label for="{{ form.attr04.id_for_label }}">errorArea['class']:</label>
                    </div>
                <div class="col-md-10">
            {{ form.attr04 }}
                </div>
            </div>
        </div>
        <div class="fieldWrapper">
            <div class='col-sm-12 col-sm-offset-1'>
                <div class="col-md-2">
            <label for="{{ form.attr05.id_for_label }}">errorCodeElement['elem']:</label>
                    </div>
                <div class="col-md-10">
            {{ form.attr05 }}
                </div>
            </div>
        </div>
        <div class="fieldWrapper">
            <div class='col-sm-12 col-sm-offset-1'>
                <div class="col-md-2">
            <label for="{{ form.attr06.id_for_label }}">errorCodeElement['class']: </label>
                    </div>
                <div class="col-md-10">
            {{ form.attr06 }}
                </div>
            </div>
        </div>
        <div class="fieldWrapper">
            <div class='col-sm-12 col-sm-offset-1'>
                <div class="col-md-2">
            <label for="{{ form.attr07.id_for_label }}">errorExplanationElement['elem']:</label>
                    </div>
                <div class="col-md-10">
            {{ form.attr07 }}
                </div>
            </div>
        </div>
        <div class="fieldWrapper">
            <div class='col-sm-12 col-sm-offset-1'>
                <div class="col-md-2">
            <label for="{{ form.attr08.id_for_label }}">errorExplanationElement['class']:</label>
                    </div>
                <div class="col-md-10">
            {{ form.attr08 }}
                </div>
            </div>
        </div>
        <div class="fieldWrapper">
            <div class='col-sm-12 col-sm-offset-1'>
                <div class="col-md-2">
            <label for="{{ form.attr09.id_for_label }}">errorSolutionElement['elem']:</label>
                    </div>
                <div class="col-md-10">
            {{ form.attr09 }}
                </div>
            </div>
        </div>
        <div class="fieldWrapper">
            <div class='col-sm-12 col-sm-offset-1'>
                <div class="col-md-2">
            <label for="{{ form.attr10.id_for_label }}">errorSolutionElement['class']:</label>
                    </div>
                <div class="col-md-10">
            {{ form.attr10 }}
                </div>
            </div>
        </div>
            <hr>
        {% else %}
        <div class="fieldWrapper">
            <div class='col-sm-12 col-sm-offset-1'>
                <div class="col-md-2">
                    <label for="{{ form.attr01.id_for_label }}">contactUrl:</label>
                </div>
                <div class="col-md-10">
                    {{ form.attr01 }}
                </div>
            </div>
        </div>
        <div class="fieldWrapper">
            <div class='col-sm-12 col-sm-offset-1'>
                <div class="col-md-2">
            <label for="{{ form.attr02.id_for_label }}">contactOrganisation:</label>
                </div>
                <div class="col-md-10">
            {{ form.attr02 }}
                </div>
            </div>
        </div>
        <div class="fieldWrapper">
            <div class='col-sm-12 col-sm-offset-1'>
                <div class="col-md-2">
            <label for="{{ form.attr03.id_for_label }}">contactArea['elem']</label>
                    </div>
                <div class="col-md-10">
            {{ form.attr03  }}
                </div>
            </div>
        </div>
        <div class="fieldWrapper">
            <div class='col-sm-12 col-sm-offset-1'>
                <div class="col-md-2">
            <label for="{{ form.attr04.id_for_label }}">contactArea['class']:</label>
                    </div>
                <div class="col-md-10">
            {{ form.attr04 }}
                </div>
            </div>
        </div>
        <div class="fieldWrapper">
            <div class='col-sm-12 col-sm-offset-1'>
                <div class="col-md-2">
            <label for="{{ form.attr05.id_for_label }}">contactNameElement['elem']:</label>
                    </div>
                <div class="col-md-10">
            {{ form.attr05 }}
                </div>
            </div>
        </div>
        <div class="fieldWrapper">
            <div class='col-sm-12 col-sm-offset-1'>
                <div class="col-md-2">
            <label for="{{ form.attr06.id_for_label }}">contactNameElement['class']:</label>
                    </div>
                <div class="col-md-10">
            {{ form.attr06 }}
                </div>
            </div>
        </div>
        <div class="fieldWrapper">
            <div class='col-sm-12 col-sm-offset-1'>
                <div class="col-md-2">
            <label for="{{ form.attr07.id_for_label }}">contactInfoElement['elem']:</label>
                    </div>
                <div class="col-md-10">
            {{ form.attr07 }}
                </div>
            </div>
        </div>
        <div class="fieldWrapper">
            <div class='col-sm-12 col-sm-offset-1'>
                <div class="col-md-2">
            <label for="{{ form.attr08.id_for_label }}">contactInfoElement['class']:</label>
                    </div>
                <div class="col-md-10">
            {{ form.attr08 }}
                </div>
            </div>
        </div>
        <div class="fieldWrapper">
            <div class='col-sm-12 col-sm-offset-1'>
                <div class="col-md-2">
            <label for="{{ form.attr09.id_for_label }}">contactPhoneElement['elem']:</label>
                    </div>
                <div class="col-md-10">
            {{ form.attr09 }}
                </div>
            </div>
        </div>
        <div class="fieldWrapper">
            <div class='col-sm-12 col-sm-offset-1'>
                <div class="col-md-2">
                    <label for="{{ form.attr10.id_for_label }}">contactPhoneElement['class']:</label>
                </div>
                <div class="col-md-10">
                    {{ form.attr10 }}
                </div>
            </div>
        </div>
        <div class="fieldWrapper">
            <div class='col-sm-12 col-sm-offset-1'>
                <div class="col-md-2">
                    <label for="{{ form.attr10.id_for_label }}">contactEmailElement['elem']:</label>
                </div>
                <div class="col-md-10">
                    {{ form.attr11 }}
                </div>
            </div>
        </div>
        <div class="fieldWrapper">
            <div class='col-sm-12 col-sm-offset-1'>
                <div class="col-md-2">
                    <label for="{{ form.attr10.id_for_label }}">contactEmailElement['class']:</label>
                </div>
                <div class="col-md-10">
                    {{ form.attr12 }}
                </div>
            </div>
        </div>
            <hr>
        {% endif %}
            <div class='col-sm-12 col-sm-offset-1'>
        {% if form.instance.pk %}
            <input type='submit' value='Updaten' class="btn btn-default"/>
        {% else %}
            <input type='submit' value='Einstellungen speichern' class="btn btn-default"/>
        {% endif %}
            </div>
    </form>
{% endblock content %}
</div>