scripts/gui/a2/urls.py
from django.conf.urls import url
from .views import (
benchmark_list, benchmark_create, benchmark_detail, benchmark_update, benchmark_delete,benchmark_start, benchmark_finish,benchmark_stop,
crawler_list, crawler_create, crawler_delete, crawler_update, crawler_detail, crawler_stop, crawler_start, crawler_finish,
benchmarkResult_create, benchmarkResult_delete,benchmark_result_detail,
crawler_result_create, crawlerResult_delete,  crawler_result_detail,
crawler_settings_create, crawler_settings_delete, crawler_settings_update, crawler_settings_detail,
)

app_name = 'a2'
urlpatterns = [
    url(r'^benchmark/$', benchmark_list, name='benchmark_list'),
    url(r'^benchmark/create/', benchmark_create, name='benchmark_create'),
    url(r'^benchmark/(?P<id>\d+)/$', benchmark_detail, name='benchmark_detail'),
    url(r'^benchmark/(?P<id>\d+)/edit/$', benchmark_update, name='benchmark_update'),
    url(r'^benchmark/(?P<id>\d+)/delete/$', benchmark_delete, name='benchmark_delete'),
    url(r'^benchmark/(?P<id>\d+)/start/$', benchmark_start, name='benchmark_start'),
    url(r'^benchmark/(?P<id>\d+)/finish/$', benchmark_finish, name='benchmark_finish'),
    url(r'^benchmark/(?P<id>\d+)/stop/$', benchmark_stop, name='benchmark_stop'),
    url(r'^benchmark/result_create/$', benchmarkResult_create, name='benchmarkResult_create'),
    url(r'^benchmark/result_detail/(?P<id>\d+)/delete/$', benchmarkResult_delete, name='benchmarkResult_delete'),
    url(r'^benchmark/result_detail/(?P<id>\d+)/$', benchmark_result_detail, name='benchmark_result_detail'),
    # url(r'^benchmark/result/$', benchmarkResult_delete, name='benchmarkResult_delete'),

    url(r'^crawler/$', crawler_list, name='crawler_list'),
    url(r'^crawler/create/', crawler_create, name='crawler_create'),
    url(r'^crawler/(?P<id>\d+)/$', crawler_detail, name='crawler_detail'),
    url(r'^crawler/(?P<id>\d+)/edit/$', crawler_update, name='crawler_update'),
    url(r'^crawler/(?P<id>\d+)/delete/$', crawler_delete, name='crawler_delete'),
    url(r'^crawler/(?P<id>\d+)/start/$', crawler_start, name='crawler_start'),
    url(r'^crawler/(?P<id>\d+)/stop/$', crawler_stop, name='crawler_stop'),
    url(r'^crawler/(?P<id>\d+)/finish/$', crawler_finish, name='crawler_finish'),

    url(r'^crawler/crawlerResult/create/', crawler_result_create, name='crawler_result_create'),
    url(r'^crawler/crawlerResult/(?P<id>\d+)/delete/$', crawlerResult_delete, name='crawlerResult_delete'),
    url(r'^crawler/crawlerResult/(?P<id>\d+)/$', crawler_result_detail, name='crawler_result_detail'),
    url(r'^crawler/(?P<id>\d+)/crawlerSettings/create/$', crawler_settings_create, name='crawler_settings_create'),
    url(r'^crawler/(?P<id>\d+)/crawlerSettings/delete/$', crawler_settings_delete, name='crawler_settings_delete'),
    url(r'^crawler/(?P<id>\d+)/crawlerSettings/edit/$', crawler_settings_update, name='crawler_settings_update'),
    url(r'^crawler/(?P<id>\d+)/crawlerSettings/$', crawler_settings_detail, name='crawler_settings_detail'),


]

scripts/gui/gui/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^a2/', include("a2.urls", namespace='a2')),
]

scripts/gui/templates/benchmark/Benchmark_detail.html
{% extends "general/base.html" %}
{% block head_title %} {{ instance.title }} | {{ block.super}} {% endblock head_title %}
{% block content %}
{% include "includes/topNav.html" %}
<div class='col-sm-10 col-sm-offset-0'>
    <h1> Detailansicht vom Benchmark: {{instance.name}}<br> <small>{{ instance.created }}</small><br></h1>
    <hr>
    <div class='row' style="background-color:#eeeeee; padding: 10px">
        <div class="col-md-4">Faktor:</div>
        <div class="col-md-8">{{ instance.factor }}</div>
    </div>
    <hr>
    <div class='row' style="background-color:#eeeeee; padding: 10px">
        <div class="col-md-4">Lesezugriffe*:<br> <small>*Im Verhältniss zu den Lese-Zugriffen</small></div>
        <div class="col-md-8">{{ instance.read_ratio }} </div>
    </div>
    <hr>
    <div class='row' style="background-color:#eeeeee; padding: 10px">
        <div class="col-md-4">Lesezugriffe*:<br> <small>*Im Verhältniss zu den Schreib-Zugriffen</small> </div>
        <div class="col-md-8">{{ instance.write_ratio }} </div>
    </div>
    <hr>
    <div class='row' style="background-color:#eeeeee; padding: 10px">
        <div class="col-md-4">Datenbanken:</div>
        {% if instance.useMongoDB %}
        <div class="col-md-4"></div><div class="col-md-8">MongoDB</div>
        {% endif %}
        {% if instance.useNoe4J %}
        <div class="col-md-4"></div><div class="col-md-8">Neo4J</div>
        {% endif %}
        {% if instance.useRedis %}
        <div class="col-md-4"></div><div class="col-md-8">Redis</div>
        {% endif %}
        {% if instance.usePostgres %}
        <div class="col-md-4"></div><div class="col-md-8">Postgres</div>
        {% endif %}
    </div>
    <hr>
    <div class='col-sm-12 col-sm-offset-0' style="padding:10px; text-align:center;">
        <p>
          <a href="{% url 'a2:benchmark_list' %}" class="btn btn-primary" role="button">OK</a>
          <a href="{{obj.get_absolute_url}}edit" class="btn btn-default" role="button">Bearbeiten</a>
          <a href="{{obj.get_absolute_url}}delete" class="btn btn-default" role="button">Löschen</a>
        </p>
</div>
{% endblock content %}
    </div>

scripts/gui/templates/benchmark/Benchmark_form.html
{% extends "general/base.html" %}
<div class='col-sm-6 col-sm-offset-3'>

{% block content %}
{% include "includes/topNav.html" %}
    <form method='POST' action=''>{% csrf_token %}
        <div class='col-sm-10 col-sm-offset-1'>
        <h1>Benchmark erstellen und bearbeiten</h1>
        <hr>
            {% for field in form %}
                {{ field.errors }}
                <div class="row">
                    <div class="col-md-3" style="padding:10px">{{ field.label_tag }}</div><div class="col-md-4">{{ field }}</div>
                </div>
                {% if field.help_text %} <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            {% endfor %}
        <hr>
        {% if form.instance.pk %}
        <input type='submit' value='Updaten' class="btn btn-default"/>
        {% else %}
        <input type='submit' value='Crawler erstellen' class="btn btn-default"/>
        {% endif %}
        </div>
    </form>
{% endblock content %}
</div>

scripts/gui/templates/benchmark/Benchmark_list.html
{% extends "general/base.html" %}

{% block content %}
{% include "includes/topNav.html" %}
<div class="col-md-12 col-md-offset-0">
    <div class="row">
    {% for obj in availability %}
        {% if obj.online %}
        <div class="col-md-3" style="color: green;"></div>
            {{ obj.name }} | online
        {% else %}
        <div class="col-md-3" style="color: red;"></div>
            {{ obj.name }} | online
        {% endif %}
    {% endfor %}
    </div>
</div>
<div class="col-md-6 col-md-offset-0">
    <div class="row">
        <h1>Benchmarks</h1>
        <hr>
    </div>
    {% for obj in object_list %}
        {% if obj.isrunning %}
            <div class="col-md-12" style="background-color:#e5ffe5; border: 1px solid #007f00; border-radius: 15px; margin-bottom: 15px">
        {% else %}
            <div class="col-md-12" style="background-color:#eeeeee; border: 1px solid #ccc; border-radius: 15px; margin-bottom: 15px">
        {% endif %}
              <div class="row">
                  <div class="col-md-12">
                    <h3><a href='{{obj.get_absolute_url}}'>{{ obj.name }} </a> <small>{{ obj.created }}</small></h3>
                      <small>
                          {% if obj.isrunning %}
                            der Benchmark läuft
                          {% endif %}
                      </small>
                  </div>
              </div>
              <div class="row" style="padding-top:10px">
                  <div class="col-md-12">
                    <div class='row' style="background-color:#eeeeee;">
                        <div class="col-md-4">Datenbanken:</div><div class="col-md-8">
                        {% if obj.useMongoDB %}
                        MongoDB,
                        {% endif %}
                        {% if obj.useNoe4J %}
                        Neo4J,
                        {% endif %}
                        {% if obj.useRedis %}
                        Redis,
                        {% endif %}
                        {% if obj.usePostgres %}
                        Postgres
                        {% endif %}
                        </div>
                    </div>
                      <div class="row">
                        <div class="col-md-4">Faktor: </div>
                        <div class="col-md-8">{{ obj.factor }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">Leserate: </div>
                        <div class="col-md-8">{{ obj.read_ratio }}</div>
                    </div>
                    <div class="row">
                        <div class="col-md-4">Schreibrate: </div>
                        <div class="col-md-8">{{ obj.write_ratio }}</div>
                    </div>
                  </div>
              </div>
              <div class="row" style="padding:15px;">
                  <p><a href="{{obj.get_absolute_url}}" class="btn btn-primary" role="button">Detailansicht</a>
                  <a href="{{obj.get_absolute_url}}edit" class="btn btn-default" role="button">Bearbeiten</a>
                  <a href="{{obj.get_absolute_url}}delete" class="btn btn-default" role="button">Löschen</a>
                  {% if obj.isrunning %}
                    <a href="{{obj.get_absolute_url}}stop" class="btn btn-default" role="button">Stop</a></p>
                  {% else %}
                    <a href="{{obj.get_absolute_url}}start" class="btn btn-default" role="button">Start</a></p>
                  {% endif %}
              </div>
          </div>
    {% endfor %}
        <p style="text-align:center;"><a href="{{obj.get_absolute_url}}create" class="btn btn-primary" role="button">Benchmark anlegen</a></p>
</div>
<div class="col-md-6 col-md-offset-0">
    <div class="row">
        <h1>bisherige Resultate</h1>
        <hr>
            {% for obj in results %}
          <div class="col-md-12" style="background-color:#eeeeee; border: 1px solid #ccc; border-radius: 15px; margin-bottom: 15px">
              <div class="row">
                  <div class="col-md-12">
                    <h1>{{ obj.crawler }}</a></h1>
                  </div>
              </div>
              <div class="row">
                  <div class="col-md-6">dataset: </div>
                  <div class="col-md-6">{{ obj.name }}</div>
              </div>
              <div class="row">
                  <div class="col-md-6">totalpages: </div>
                  <div class="col-md-6">{{ obj.created }}</div>
              </div>
              <div class="row">
                  <div class="col-md-6">crawledpages: </div>
                  <div class="col-md-6">{{ obj.benchmark.name }}</div>
              </div>
                <div class="row" style="padding:15px;">
                  <p><a href="{{obj.get_absolute_url}}" class="btn btn-primary" role="button">Detailansicht</a>
                  <a href="{{obj.get_absolute_url}}delete/" class="btn btn-default" role="button">Löschen</a>
              </div>
          </div>
    {% endfor %}
        <hr>
    </div>
</div>
{% endblock content %}
</div>

scripts/gui/templates/benchmark/base.html
{% load staticfiles %}
<!-- DOCTYPE html -->
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block head_title %} Try Django 1.9 {% endblock head_title %}
    </title>
    <link rel='stylesheet' href='{% static "css/base.css" %}' >
    <link rel='stylesheet' href='{% static "css/bootstrap.css" %}' >
    <!-- Latest compiled and minified CSS -->
<!--<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">-->

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

</head>
<body>
{% block nav %}
<ul id="nav">
    <li>{% block nav-crawler %}<a href="{% url crawler %}">crawler</a>{% endblock %}</li>
    <li>{% block nav-benchmark %}<a href="{% url benchmark %}">benchmark</a>{% endblock %}</li>
</ul>
{% endblock %}
{% include "includes/messages_display.html" %}
<div class='container'>
    {% block content %}

    {% endblock content %}
</div>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</body>
</html>

scripts/gui/templates/benchmark/benchmark_result_detail.html
{% extends "general/base.html" %}
{% block head_title %} {{ instance.title }} | {{ block.super}} {% endblock head_title %}
{% block content %}
{% include "includes/topNav.html" %}
<div class='col-sm-10 col-sm-offset-0'>
    <h1> Detailansicht vom Benchmark Ergebnis: <br>{{instance.name}} <br><small>vom {{ instance.created }}</small><br></h1>
    <hr>
    {% for obj in records %}
    <p>
        {{obj.created}} | {{obj.types}} | {{obj.databases}} | {{obj.operations}} | {{obj.operations}} | {{obj.amount}} | {{obj.time}}
    </p>
    {% endfor %}
    <hr>
    <div class='col-sm-12 col-sm-offset-0' style="padding:10px; text-align:center;">
        <p>
          <a href="{% url 'a2:benchmark_list' %}" class="btn btn-primary" role="button">OK</a>
          <a href="{{obj.get_absolute_url}}delete" class="btn btn-default" role="button">Löschen</a>
        </p>
    </div>
</div>
{% endblock content %}

scripts/gui/templates/benchmark/overview.html
{% extends "general/base.html" %}

{% block content %}
<div class='col-sm-8 col-sm-offset-2'>
    <h1>{{title}}</h1>
    <div class="row">
    {% for obj in object_list %}
          <div class="col-sm-12">
            <div class="thumbnail">
              <!--<img src="..." alt="...">-->
              <div class="caption">
                <h3><a href='{{obj.get_absolute_url}}'>{{ obj.title }}</a> <small>{{ obj.created }}</small></h3>
                <p>{{ obj.content|linebreaks|truncatechars:120 }}</p>
                  <p><small>Updated: {{ obj.updated }}</small></p>
                  <p><small>Id: {{ obj.id }}</small></p>
                <p><a href="{{obj.get_absolute_url}}" class="btn btn-primary" role="button">Button</a> <a href="#" class="btn btn-default" role="button">Button</a></p>
              </div>
            </div>
                      <hr>
          </div>

    {% cycle "" "</div><div class='row'>" %}
    {% endfor %}
    </div>
</div>
{% endblock content %}